### ISSUE TITLE
softethervpn5-server configure file could't be kept when system upgrade

### ISSUE THREAD

**Issue by xinxijishuwyq** [Andy2244/openwrt-extra#11]
I use your code to build softethervpn5-server. And install "softethervpn5-libs_2018-10-03-2271bf5f-1_x86_64.ipk" and "softethervpn5-server_2018-10-03-2271bf5f-1_x86_64.ipk" to my x86 based router. It works well except the configure file(vpn_server.config)  could't be kept when system upgrade. 

![50324790-f25dcc00-051b-11e9-9de4-17d1e1e9f138](https://user-images.githubusercontent.com/1755898/50379882-d0865580-0691-11e9-9360-efcb44be21c2.png)
![50324789-f25dcc00-051b-11e9-9211-09926a923ba8](https://user-images.githubusercontent.com/1755898/50379883-d4b27300-0691-11e9-84ea-d37cf2706484.png)
![50324791-f25dcc00-051b-11e9-8bb7-9a02022a9274](https://user-images.githubusercontent.com/1755898/50379885-d7ad6380-0691-11e9-8e04-442fa7d925ac.png)

**Comment by Andy2244** [comment]
Thanks will try to check why the config file is not kept.

**Comment by lars18th** [comment]
Hi,

If you read about the problem of the user configuration from packages when upgrading:
- https://openwrt.org/docs/guide-user/troubleshooting/backingup
- https://openwrt.org/docs/guide-user/installation/generic.sysupgrade

Then you can see that the problem is because the configuration of the SoftEtherVPN5 is stored inside the directory `/usr/libexec/softethervpn/` .

So, you need to add it to the file `/etc/sysupgrade.conf`:
```
## This file contains files and directories that should
## be preserved during an upgrade.

# /etc/example.conf
# /etc/openvpn/
```

Futhermore I suggest to add the file `softethervpn5/files/softethervpn5.upgrade` to identify the config files required to preserve when upgrading the package (useful when you "reinstall" the package and the files already exist). See these example:
- https://github.com/openwrt/packages/blob/master/net/privoxy/files/privoxy.upgrade
- https://github.com/openwrt/packages/blob/master/net/vpnc/files/vpnc.upgrade

I hope it helps! :wink:

**Comment by Andy2244** [comment]
This should be already fixed, config files don't necessary have to be inside /etc, from my last test the config files are now preserved and also included in the backup from luci. I think it was a problem in the definition file.
I get this, without any additional entries in `/etc/sysupgrade.conf`

`opkg list-changed-conffiles`
...
```
/etc/config/samba4
/etc/samba/smb.conf.template
/usr/libexec/softethervpn/vpn_server.config
/etc/config/sqm
/etc/config/uhttpd
```

Did not actually know about /lib/upgrade/keep.d, but it seems files are also auto-generated there, since i get entries for softethervpn, cifsd-tools, samba4 there without manually creating those. The strange part is while cifsd-tools has all it defined config files, softethervpn only gas the .lang file it it. Need to poke chat to see whats going on there.

**Comment by lars18th** [comment]
> Need to poke chat to see whats going on there.

I think so!

**Comment by Andy2244** [comment]
Jow just confirmed, there is rarely a reason to directly use /lib/upgrade/keep.d, this should be handled by conffiles. I also get all files in the backup, so i assume this is fixed? 
Maybe someone else can confirm this?

**Comment by Andy2244** [comment]
@xinxijishuwyq can you retest if this has been fixed for you now?
